app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    
#Create class for Users
class User(UserMixin,db.Model):
    '''
    Class to define users
    '''
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key= True)
    username = db.Column(db.String(255))
    email = db.Column(db.String,unique = True)
    pitches = db.relationship("Pitch", backref = 'user', lazy = "dynamic")
    bio = db.Column(db.String(255))
    profile_pic_url = db.Column(db.String())
    pass_secure = db.Column(db.String(255))

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    
    @property
    def password(self):
        raise AttributeError ('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User{self.username}'

class Category(db.Model):
    __tablename__ = 'categories'

    id = db.Column(db.Integer,primary_key= True)
    category_name = db.Column(db.String())
    pitches = db.relationship("Pitch", backref ="category", lazy= "dynamic")

    @classmethod
    def get_category_name(cls,category_name):
        categoryName = Category.query.filter_by(category_name = category_name).first()
        return categoryName.id

    def __repr__(self):
        return f'Category{self.category_name}' 

    
class Pitch(db.Model):
    __tablename__ = 'pitches'
    
    id = db.Column(db.Integer,primary_key= True)
    title = db.Column(db.String())
    description = db.Column(db.String())
    date = db.Column(db.DateTime,default=datetime.utcnow)
    upvotes = db.Column(db.Integer)
    downvotes = db.Column(db.Integer)
    category_id = db.Column(db.Integer, db.ForeignKey("categories.id"))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship("Comment", backref ='pitch', lazy = "dynamic")
  
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_user_pitch(cls,id):
        user_pitches = Pitch.query.filter_by(user_id = id).all()
        return user_pitches

    @classmethod
    def get_category_pitch(cls,id):
        category_pitches = Pitch.query.filter_by(category_id = id).all()
        return category_pitches


    def __repr__(self):
        return f"Pitch {self.title}"

class Comment(db.Model):
    __tablename__ = "comments"

    id = db.Column(db.Integer, primary_key = True)
    content = db.Column(db.String())
    date =db.Column(db.DateTime,default = datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))


    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(pitch_id = id).all()
        return comments

app/main/forms.py
from . import main
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField,StringField, SelectField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField("Tell us about you.", validators=[Required()])
    submit = SubmitField("Submit Bio")

class addPitch(FlaskForm):
    title = StringField("Pitch Title", validators = [Required()])
    category = SelectField("What is the type of pitch", choices=[("funny", "funny"), ("brainy", "brainy"), ("romantic", "romantic"), ("inspirational", "inspirational"),( "random", "random"), ("business", "business"), ("spiritual", "spiritual")],validators=[Required()])
    description = TextAreaField("Enter Pitch", validators = [Required()])
    submit = SubmitField("Add Pitch")

class addComment(FlaskForm):
    content = TextAreaField("Add Comment")
    submit = SubmitField("Add")

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
# from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail

db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
# photos = UploadSet('photos', IMAGES)
mail = Mail()


def create_app(config_name):
    app = Flask(__name__)

    #Creating app configuration
    app.config.from_object(config_options[config_name])

    #initializing flask extenxtion
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    #configure uploadset
    # configure_uploads(app,photos)

    #Registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required, current_user
from app.models import User, Pitch, Category, Comment
from .forms import UpdateProfile,addPitch,addComment
from .. import db
from datetime import datetime

@main.route('/')
def index():
    '''
    View root page function that returns the index page and it's data
    '''
    categories = Category.query.all()
    title = "The pitcher"
    return render_template('index.html', title = title, categories = categories )

@main.route('/pitches/<category_id>')
def pitches_by_category(category_id):
    '''
    View pitches page function that displays the picthes available
    '''
    pitches = Pitch.get_category_pitch(category_id)

    return render_template('pitches.html', pitches = pitches)

@main.route('/user/ <uname>/addpitch',methods =['GET', 'POST'])
@login_required
def add_pitch(uname):
    title = "Add pitch"
    form = addPitch()
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    if form.validate_on_submit():
        title = form.title.data
        categorydata = form.category.data
        category_id = (Category.get_category_name(categorydata))
        description = form.description.data
        upvotes = 0
        downvotes = 0
        
        
        new_pitch = Pitch(title=title, category_id = category_id, description = description, user = user, upvotes = upvotes, downvotes = downvotes)
        new_pitch.save_pitch()

        return redirect(url_for("main.index"))
    return render_template("addpitch.html", form = form, title = title)
        


@main.route('/user/<uname>')
def profile(uname):
    user = User. query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    pitches = Pitch.get_user_pitch(user.id)

    return render_template("profile/profile.html", pitches = pitches , user = user)


@main.route('/user/<uname>/update', methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    
    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname = user.username))

    return render_template('profile/update.html', form = form)

@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_url = path
        db.session.commit()

    return redirect(url_for('main.profile', uname = uname))

@main.route("/<user>/<pitch_id>/addcomment", methods = ['GET', 'POST'])
@login_required
def comment(user,pitch_id):
    user= User.query.filter_by(id = user).first()
    user_id = user.id
    pitch = Pitch.query.filter_by(id = pitch_id).first()
    pitcher_id = pitch.id
    print('-'*75)
    print(pitcher_id)
    title = "Add Comment"
    form = addComment()
    if form.validate_on_submit:
        content = form.content.data
        new_comment = Comment(content= content, user_id = user_id, pitch_id = pitcher_id)
        new_comment.save_comment()

        return redirect(url_for('main.index'))

    return render_template("comment.html", title = title,form = form, pitch = pitch)

app/templates/addpitch.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}

{% block content%}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    {% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static',filename='css/base.css')}}" type="text/css">
  {% endblock %}
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>
© 2020 GitHub, Inc.

app/templates/index.html
{% extends 'base.html' %}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Lato:wght@400;700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div id="header">     
        <h1><img src="{{url_for('static',filename='photos/mic.png')}}"" alt=""> THE PITCHER</h1> 
        <h4>It only takes one minute to make an impression</h4>
        <h5>make it as fantastic as possible,it provides alot of ideas and decisions to be made</h5>
        <h6>dont forget to subscribe if you are not a user</h6>
    </div>
    
    <br>
    <h2>CATEGORIES</h2>
    <div class=" row">
            {% for category in categories %}
            <div id="category" class="col-md-6">
                <p>{{category.category_name}}</p>

                <a href="{{url_for('main.pitches_by_category', category_id = category.id)}}"><button
                        class="btn btn-outline info">View Pitches </button> </a>
                <hr>
            </div>
            {% endfor %}
    </div>

</div>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id ="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">HOME</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.add_pitch', uname=current_user.username)}}"> Add pitches</a></li>
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}'s Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>

    </div>
</div>

app/templates/pitches.html
{% extends 'base.html' %}


{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/pitches.css')}}" type="text/css">
<link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Lato:wght@400;700&display=swap"
    rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
{% endblock %}

<div class="container">
    {% block content %}
    <h1>PITCHES</h1>

    {% if pitches %}
    {% for pitch in pitches %}
    <div id="card">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">{{pitch.title}}</h2>
                <h6 class="card-subtitle mb-2 text-muted">Submitted on :{{pitch.date}}</h6>
                <p class="card-text">Pitch: {{pitch.description}}</p>
                <button class="btn btn-outline-info"><a href="{{url_for('main.comment',user = current_user.id, pitch_id = pitch.id)}}">Add Comment </a></button>
            </div>
        </div>
    </div>
    {% endfor %}
    {%else %}
    <p id ="nothing">There are no pitches in this category</p>
    {% endif %}
    {% endblock %}
</div>

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">
<link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Lato:wght@400;700&display=swap"
    rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <h2>{{user.username| capitalize}}'s Profile</h2>

    <div class="row">
        <div class="col-md-3">
            {% if user.profile_pic_url %}
            <img src="{{url_for('static',filename=user.profile_pic_url)}}" alt="" class="img-thumbnail">
            {%else%}
            <img src="{{url_for('static',filename='photos/pic.png')}}""  alt=""class=" img-thumbnail">
            {% endif %}
        </div>
        <div class="col-md-8">
            <h3>Bio</h3>
            <div class="row">
                <div class="col-md-6">
                    {% if user.bio %}

                    <h4> {{user.bio}}</h4>
                    {%else%}
                    <h4> {{user.username| capitalize}} has no bio </h4>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    {% if user == current_user %}
                    <button class="btn btn-outline-info"><a
                            href="{{url_for('main.update_profile',uname=user.username)}}">leave a comment</a></button>
                    {% endif %}
                </div>
            </div>

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">
                <label id="label"> Edit Profile Pic</label>
                <input type="file" name="photo" class="form-control" required>
                <input type="submit" class="btn btn-outline-info">
            </form>
            {% endif %}
        </div>
    </div>

    <h2>My Pitches</h2>
    <h3>God is the way ,the truth and the life and however believes in him shall inherit kingdom of heaven</h3>
    <h4>I choose God ,I choose happiness and greatness</h4>
    <h2>colouring this life like its all in crayons<h2/>
    <h3>the will to destroy or compose your life all lies in your hands</h3>
    <h2>Time is one assert that awaits for no man so make use of the very little time that you have</h2>
    {% for pitch in pitches %}
    <div id="card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">{{pitch.title}}</h3>
                <h6 class="card-subtitle mb-2 text-muted">Submitted on :{{pitch.date}}</h6>
                <p class="card-text">Pitch: {{pitch.description}}</p>
                <a href="{{url_for('main.comment',user = current_user.id, pitch_id = pitch.id)}}"
                    class="btn btn-outline-info"> Add Comment </a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}